# AutoTotem: by blujay

# Found a bug? Report it on the github! https://github.com/blu-jay/AutoTotem
# Please consider reviewing the plugin on spigot :)

#config version, DO NOT CHANGE THIS!
version: 2

# Cool down between auto totem uses. (In Seconds)
# this can be overwritten by giving players the autototem.bypass permission
cooldown: 0

# Should vanilla totem use (Using a totem of undying normally by holding it in your hand) be effected by cooldowns?
includeVanillaTotemsInCooldown: false

# Should AutoTotem only use totems from the hot bar?
hotBarOnly: false